# Generated by Django 3.0.7 on 2020-07-27 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=110)),
                ('description', models.TextField(default='null')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.FloatField()),
                ('note', models.FloatField()),
                ('wine_category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='wine_app.Category')),
            ],
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(default='null', upload_to='images')),
                ('image2', models.ImageField(default='null', upload_to='images')),
                ('image3', models.ImageField(default='null', upload_to='images')),
                ('wine', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='wine_app.Wine')),
            ],
        ),
    ]
