# Generated by Django 3.0.7 on 2020-07-14 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Vin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=110)),
                ('descriere', models.TextField(default='null')),
                ('cantitate', models.IntegerField(default=1)),
                ('imagine', models.CharField(default='null', max_length=110)),
                ('pret', models.FloatField()),
                ('nota', models.FloatField()),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='wine_app.Categorie')),
            ],
        ),
    ]
