# Generated by Django 3.0.7 on 2020-07-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postimage',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='postimage',
            name='image2',
            field=models.ImageField(default='null', upload_to='images'),
        ),
        migrations.AddField(
            model_name='postimage',
            name='image3',
            field=models.ImageField(default='null', upload_to='images'),
        ),
    ]
