# Generated by Django 3.0.7 on 2020-07-19 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wine_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='wine_app.Vin')),
            ],
        ),
    ]
