# Generated by Django 3.0.7 on 2020-07-27 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wine_app', '0002_auto_20200727_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wine',
            name='image',
        ),
    ]
