# Generated by Django 3.0.7 on 2020-07-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine_app', '0002_poza'),
    ]

    operations = [
        migrations.AddField(
            model_name='poza',
            name='picture',
            field=models.ImageField(default='null', upload_to='images'),
        ),
    ]
