# Generated by Django 3.0.7 on 2020-07-22 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wine_app', '0003_poza_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('picture', models.ImageField(default='null', upload_to='images')),
                ('vin_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='wine_app.Vin')),
            ],
        ),
        migrations.DeleteModel(
            name='Poza',
        ),
    ]
