# Generated by Django 3.0.7 on 2020-07-22 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wine_app', '0004_auto_20200722_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='vin_id',
            new_name='vin',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='name',
        ),
    ]
