# Generated by Django 3.0.7 on 2020-07-27 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wine_app', '0004_auto_20200727_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wine',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='wine',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='wine',
            name='image3',
        ),
    ]
