# Generated by Django 3.0.7 on 2020-07-22 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine_app', '0005_auto_20200722_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='nume',
            field=models.CharField(default='null', max_length=110),
        ),
    ]
