# Generated by Django 3.0.7 on 2020-07-22 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wine_app', '0006_picture_nume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='nume',
        ),
    ]
