# Generated by Django 3.0.7 on 2020-07-22 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wine_app', '0007_remove_picture_nume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vin',
            name='imagine',
        ),
    ]
